### PR TITLE
38 merge

### PR DESCRIPTION
**Pull request by jchlanda**
This PR brings llvm-leg to release_38 of llvm (https://github.com/llvm-mirror/llvm/tree/release_38/).

### CODE REVIEW

**Comment by frasercrmck** [comment]
@pasaulais Want to help take a look?

**Comment by pasaulais** [comment]
+1 Looks good to me (the only changes in lib/Target/LEG seem to be adding `override` to some functions)

**Comment by frasercrmck** [comment]
There are a few files which I guess are from your mac? `lib/Analysis/.DS_Store`, for example. I'll try and get rid of those. Apart from that, it all looks good. Just building and running tests now.

I'll create and push this as a `release_38` branch, and merge it into master

**Comment by frasercrmck** [comment]
Oh, and create a `release_37` from the current master

**Pull request merged**
